# Generated by Django 3.0.6 on 2026-04-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0017_auto_20210126_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
